# Build with:
# docker-compose build

# Run with:
# docker-compose up

version: '2.2'

services:
  elastic01:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.0.0
    environment:
      - node.name=elastic01
      - cluster.initial_master_nodes=elastic01,elastic02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      elk:


  elastic02:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.0.0
    environment:
      - node.name=elastic02
      - discovery.seed_hosts=elastic01
      - cluster.initial_master_nodes=elastic01,elastic02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - esdata02:/usr/share/elasticsearch/data
    ports:
      - 9200
    networks:
      - elk


  elasticslave:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.0.0
    environment:
      - node.master=false
      - discovery.seed_hosts=elastic01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200
    networks:
      - elk


  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.0.0
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "5044:5044"
    networks:
      - elk
    depends_on:
      - kibana
      - elastic01

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.0.0
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elastic01

networks:
  elk:
    driver: bridge

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
